'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';
import AboutSection from '@/components/AboutSection';
import FeaturedProductsSection from '@/components/FeaturedProductsSection';
import ServicesSection from '@/components/ServicesSection';
import PortfolioGallery from '@/components/PortfolioGallery';
import BookingSystem from '@/components/BookingSystem';
import FAQSection from '@/components/FAQSection';
import CTASection from '@/components/CTASection';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
        <AboutSection />
        <FeaturedProductsSection />
        <ServicesSection />
        <PortfolioGallery />
        <BookingSystem />
        <FAQSection />
        <CTASection />
      </main>
    </>
  );
}